Traceback (most recent call last):
  File "HAPLOID.py", line 226, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 200, in displayResults
    for type in analysis[uhla][pos][:-1]:
TypeError: unhashable type
Traceback (most recent call last):
  File "HAPLOID.py", line 252, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 224, in displayResults
    for aa in analysis[uhla][pos][truth]:
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "HAPLOID.py", line 248, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 227, in displayResults
    print '<td>{}</td>'.format()
IndexError: tuple index out of range
Traceback (most recent call last):
  File "HAPLOID.py", line 253, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 225, in displayResults
    for aa in analysis[uhla][pos][truth]:
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "HAPLOID.py", line 252, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 229, in displayResults
    tt = analysis[uhla][pos][truth][aa]
TypeError: 'int' object is not subscriptable
Traceback (most recent call last):
  File "HAPLOID.py", line 252, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 229, in displayResults
    tt = analysis[uhla][pos]['tt'][aa]
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "HAPLOID.py", line 253, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 230, in displayResults
    tt = analysis[uhla][pos]['tt'][aa]
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "HAPLOID.py", line 253, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 230, in displayResults
    tt = analysis[uhla][pos]['tt'][aa]
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "HAPLOID.py", line 253, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 230, in displayResults
    tt = analysis[uhla][pos]['tt'][aa]
KeyError: 'Q'
Traceback (most recent call last):
  File "HAPLOID.py", line 254, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 225, in displayResults
    for aa in [set(seqmatrix[x][pos]) for x in seqmatrix]:
TypeError: list indices must be integers, not list
Traceback (most recent call last):
  File "HAPLOID.py", line 255, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 226, in displayResults
    for aa in set([seqmatrix[x][pos] for x in seqmatrix]):
TypeError: list indices must be integers, not list
Traceback (most recent call last):
  File "HAPLOID.py", line 255, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 232, in displayResults
    tt = analysis[uhla][pos]['tt'][aa]
KeyError: 'Q'
Traceback (most recent call last):
  File "HAPLOID.py", line 256, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 224, in displayResults
    for aa in [x for x in analysis[uhla][pos][x]]:
UnboundLocalError: local variable 'x' referenced before assignment
Traceback (most recent call last):
  File "HAPLOID.py", line 256, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 229, in displayResults
    tt = analysis[uhla][pos]['tt'][aa]
KeyError: 'Q'
Traceback (most recent call last):
  File "HAPLOID.py", line 255, in <module>
    displayResults(results, patients)
  File "HAPLOID.py", line 240, in displayResults
    print '<td>{}</td>'.format(tt)
UnboundLocalError: local variable 'tt' referenced before assignment
Traceback (most recent call last):
  File "HAPLOID.py", line 257, in <module>
    displayResults(results, patients)
TypeError: displayResults() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "HAPLOID.py", line 267, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 249, in displayResults
    print '<td>{}</td>'.format(direction)
NameError: global name 'direction' is not defined
Traceback (most recent call last):
  File "HAPLOID.py", line 271, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 258, in displayResults
    print '<td>{}</td>'.format(n)
UnboundLocalError: local variable 'n' referenced before assignment
Traceback (most recent call last):
  File "HAPLOID.py", line 286, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 223, in displayResults
    for pot in analysis[uhla][pos]['tf']:
KeyError: 'tf'
Traceback (most recent call last):
  File "HAPLOID.py", line 291, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 246, in displayResults
    ff += mixft[aa]
KeyError: 'Q'
Traceback (most recent call last):
  File "HAPLOID.py", line 291, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 246, in displayResults
    ff += mixft[aa]
KeyError: 'Q'
Traceback (most recent call last):
  File "HAPLOID.py", line 291, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 246, in displayResults
    ff += mixft[aa]
KeyError: 'Q'
Traceback (most recent call last):
  File "HAPLOID.py", line 291, in <module>
    displayResults(results,len(patients))
  File "HAPLOID.py", line 246, in displayResults
    ff += mixft[aa]
KeyError: 'Q'
